improbe check script

diff --git a/.github/workflows/dotnet-deploy.yml b/.github/workflows/dotnet-deploy.yml
--- a/.github/workflows/dotnet-deploy.yml
+++ b/.github/workflows/dotnet-deploy.yml
@@ -16,7 +16,7 @@ env:
   resourceGroup: openhackkkg4t772poi
   subscriptionId: 03a6d591-1096-4413-9cf4-ae9bb9a8f348
   healthCheckUrl: https://openhackkkg4t772poi-staging.azurewebsites.net/api/healthcheck/poi
-
+  dockerImageName: api-po
 
 jobs:
   build-and-deploy:
@@ -35,8 +35,8 @@ jobs:
         run: echo ${{ github.run_number }}
 
       - run: |
-          docker build . -t openhackkkg4t772acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}
-          docker push openhackkkg4t772acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}
+          docker build . -t openhackkkg4t772acr.azurecr.io/devopsoh/${{ env.dockerImageName }}:${{ github.run_number }}
+          docker push openhackkkg4t772acr.azurecr.io/devopsoh/${{ env.dockerImageName }}:${{ github.run_number }}
       
       - name: Azure Login
         uses: azure/login@v1
@@ -55,7 +55,7 @@ jobs:
           app-name: 'openhackkkg4t772poi'
           slot-name: staging
           publish-profile: ${{ secrets.API_POI_STAGING_DEPLOYMENT_PROFILE }}
-          images: 'openhackkkg4t772acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}'
+          images: 'openhackkkg4t772acr.azurecr.io/devopsoh/${{ env.dockerImageName }}:${{ github.run_number }}'
 
       - name: Restart the slot
         uses: azure/CLI@v1
@@ -68,18 +68,23 @@ jobs:
         id: 'checkDeployment'
         continue-on-error: true
         run: |
-          # url="https://openhackkkg4t772poi-staging.azurewebsites.net/api/healthcheck/poi"
           url=${{ env.healthCheckUrl }}
-          result=$(curl -i $url 2>/dev/null | grep HTTP/2)
-          status=${result:7:3}
 
-          if [[ "$status" = "200" ]]; then
-            echo "200"
-            exit 0  
-          else
-            echo "not 200"
-            exit 1
-          fi
+          for i in $(seq 1 10)  
+          do 
+            result=$(curl -i $url 2>/dev/null | grep HTTP/2)
+            status=${result:7:3}
+
+            if [[ "$status" = "200" ]]; then
+              echo "200"
+              exit 0  
+            fi
+
+            sleep 10
+          done
+
+          # It failed a lot of time
+          exit 1
 
       # TODO: Create issue if not
       - name: Create Issue
@@ -96,7 +101,7 @@ jobs:
         if: success()
         with:
           inlineScript: |
-            az webapp deployment slot swap --slot staging --targe-slot production --name ${{ env.webappName }} --resource-group ${{ env.resourceGroup }} --subscription ${{ env.subscriptionId }}          
+            az webapp deployment slot swap --slot staging --target-slot production --name ${{ env.webappName }} --resource-group ${{ env.resourceGroup }} --subscription ${{ env.subscriptionId }}          
 
       - name: Stop slot
         uses: azure/CLI@v1
